import isEmpty from './tools/is-empty';
import isName from './tools/is-name';
import isPhone from './tools/is-phone';
import isTel from './tools/is-tel';
import isEmail from './tools/is-email';
import isIdCard from './tools/is-id-card';
import isMoney from './tools/is-money';
import setCookie from './tools/set-cookie';
import setSessionStorage from './tools/set-session-storage';
import setLocalStorage from './tools/set-local-storage';
import getCookie from './tools/get-cookie';
import getSessionStorage from './tools/get-session-storage';
import getLocalStorage from './tools/get-local-storage';
import getVarType from './tools/get-var-type';
import getUaInfo from './tools/get-ua-info';
import formatBlobUrl from './tools/format-blob-url';
import formatJsonSearch from './tools/format-json-search';
import formatSearchJson from './tools/format-search-json';
import formatMoneyNumCapital from './tools/format-money-num-capital';
import formatDate from './tools/format-date';
import formatMoneySymbol from './tools/format-money-symbol';
import limitInt from './tools/limit-int';
import limitIntFloat from './tools/limit-int-float';
import limitPNInt from './tools/limit-p-n-int';
import limitPNIntFloat from './tools/limit-p-n-int-float';
import loadScript from './tools/load-script';
import loadScriptAwait from './tools/load-script-await';
import creatUuid from './tools/creat-uuid';
import extend from './tools/extend';
import fillZero from './tools/fill-zero';
import downBlobFile from './tools/down-blob-file';
import loactionReplace from './tools/loaction-replace';
import copyText from './tools/copy-text';
export { isEmpty, isName, isPhone, isTel, isEmail, isIdCard, isMoney, setCookie, setSessionStorage, setLocalStorage, getCookie, getSessionStorage, getLocalStorage, getVarType, getUaInfo, formatDate, formatMoneySymbol, formatMoneyNumCapital, formatBlobUrl, formatJsonSearch, formatSearchJson, limitInt, limitIntFloat, limitPNInt, limitPNIntFloat, loadScript, loadScriptAwait, creatUuid, extend, fillZero, downBlobFile, loactionReplace, copyText, };
declare const _default: {
    isEmpty: (params?: any) => boolean;
    isName: (val: string) => boolean;
    isPhone: (val: string) => boolean;
    isTel: (val: string) => boolean;
    isEmail: (val: string) => boolean;
    isIdCard: (val: string) => boolean;
    isMoney: (val: string | number) => boolean;
    setCookie: (key: string, value: string, { domain, path, expires, secure }?: any) => void;
    setSessionStorage: (key: string, val: any) => any;
    setLocalStorage: (key: string, val: any) => any;
    getCookie: (key: string) => any;
    getSessionStorage: (key: string) => any;
    getLocalStorage: (key: string) => any;
    getVarType: (o: any) => string;
    getUaInfo: () => object;
    formatDate: (date: any, fmt?: string) => string;
    formatMoneySymbol: (money: string | number) => string | number | null;
    formatMoneyNumCapital: (n: number, h: string) => string;
    formatBlobUrl: (blob: any) => any;
    formatJsonSearch: (myJson: any, connector?: string) => string;
    formatSearchJson: (search: string) => object;
    limitInt: (val: string | number) => string;
    limitIntFloat: (val: string | number, digit: number) => number;
    limitPNInt: (val: string | number) => string;
    limitPNIntFloat: (val: string | number, digit: number) => number;
    loadScript: (scripts: string | string[]) => Promise<boolean>;
    loadScriptAwait: (scripts: string | string[]) => Promise<void>;
    creatUuid: (len?: number | undefined, radix?: number | undefined) => string;
    extend: (target: any, ...args: any) => object;
    fillZero: (num: string | number) => string | number;
    downBlobFile: (blob: any, { name, suffix }?: any) => void;
    loactionReplace: (url: string) => void;
    copyText: (str: string) => boolean;
};
export default _default;
